# Generated by Django 4.1.5 on 2023-04-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0009_dataset_creation_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origin',
            old_name='origin_status_id',
            new_name='origin_status',
        ),
    ]
