# Generated by Django 4.1.5 on 2023-04-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0011_rename_origin_id_dataset_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_type_id',
            new_name='report_type',
        ),
    ]
